#!/bin/bash

#
# $Id$
#
# Builds the revision number.
#

rev=`svn info | awk '/Revision/{print $2}' | head -n 1`
rdate=`svn info | awk '/Last Changed Date/{print $4}' | head -n 1`

if [ -z "$rev" ]; then
  if [ -e revision.h ]; then
    printf "Leaving old revision number\n"
  else
    printf "Using bogus revision number\n";
    printf "const int REVISION_NUMBER = 0 ;\n" > revision.h
    printf "const char* REVISION_DATE = \"%s\";\n" $rdate >> revision.h
  fi
  exit 0
fi
if [ -e revision.h ]; then
  revlast=`awk '{print $5}' revision.h | head -n 1`
  if [ "$rev" -eq "$revlast" ]; then
    printf "No revision number change since last build\n";
    exit 0
  fi
fi
printf "Updating revision number to %d\n" $rev
printf "const int REVISION_NUMBER = $rev ;\n" > revision.h
printf "const char* REVISION_DATE = \"%s\";\n" $rdate >> revision.h
